function signature = build_run_cache_signature(cfg)
    signature = struct( ...
        'num_eeg_channels', cfg.num_eeg_channels, ...
        'raw_fs', cfg.raw_fs, ...
        'filter_cfg', cfg.filter_cfg, ...
        'bad_channel_cfg', cfg.bad_channel_cfg, ...
        'decimation_factor', cfg.decimation_factor, ...
        'ica_cfg', cfg.ica_cfg, ...
        'epoch_cfg', cfg.epoch_cfg, ...
        'movement_codes', cfg.movement_codes, ...
        'erp_channel_label', cfg.erp_channel_label);
end
