function cfg = load_project_config()
    project_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    run(fullfile(project_root, 'constants.m'));

    cfg = struct( ...
        'project_root', project_root, ...
        'data_root', resolve_project_path(project_root, data_root), ...
        'output_root', resolve_project_path(project_root, output_root), ...
        'figures_root', resolve_project_path(project_root, figures_root), ...
        'tables_root', resolve_project_path(project_root, tables_root), ...
        'cache_root', resolve_project_path(project_root, cache_root), ...
        'results_path', resolve_project_path(project_root, results_path), ...
        'binica_support_dir', resolve_project_path(project_root, binica_support_dir), ...
        'run_cache_cfg', run_cache_cfg, ...
        'num_subjects', num_subjects, ...
        'num_runs', num_runs, ...
        'num_eeg_channels', num_eeg_channels, ...
        'raw_fs', raw_fs, ...
        'filter_cfg', filter_cfg, ...
        'bad_channel_cfg', bad_channel_cfg, ...
        'decimation_factor', decimation_factor, ...
        'ica_cfg', ica_cfg, ...
        'epoch_cfg', epoch_cfg, ...
        'movement_codes', movement_codes, ...
        'movement_labels', {movement_labels}, ...
        'report_cfg', resolve_report_cfg_paths(project_root, report_cfg));

    cfg.processed_fs = resolve_processed_fs(cfg.raw_fs, cfg.decimation_factor);
    cfg.num_classes = numel(cfg.movement_codes);
    cfg.bad_channel_cfg.sample_rate_hz = cfg.raw_fs;
end

function report_cfg = resolve_report_cfg_paths(project_root, report_cfg)
    report_cfg.d1_bad_channels_csv = resolve_project_path(project_root, report_cfg.d1_bad_channels_csv);
    report_cfg.d2_good_trials_csv = resolve_project_path(project_root, report_cfg.d2_good_trials_csv);
end

function absolute_path = resolve_project_path(project_root, path_value)
    path_value = char(path_value);
    if is_absolute_path(path_value)
        absolute_path = path_value;
    else
        absolute_path = fullfile(project_root, path_value);
    end
end

function tf = is_absolute_path(path_value)
    tf = startsWith(path_value, filesep) || ~isempty(regexp(path_value, '^[A-Za-z]:[\\/]', 'once'));
end
