function cfg = bad_channel_cfg_apply_defaults(cfg)
    default_fields = struct( ...
        'z_threshold', 5, ...
        'corr_z_threshold', [], ...
        'var_z_threshold', [], ...
        'range_z_threshold', [], ...
        'kurt_z_threshold', [], ...
        'use_correlation', true, ...
        'use_variance', true, ...
        'use_range', true, ...
        'use_kurtosis', true, ...
        'normalization', 'trimmed', ...
        'trim_percent', 10, ...
        'use_segmented_windows', false, ...
        'segment_length_sec', 2, ...
        'segment_step_sec', 1, ...
        'segment_z_threshold', 5, ...
        'segment_bad_fraction', 0.5, ...
        'sample_rate_hz', []);

    default_names = fieldnames(default_fields);
    for field_idx = 1:numel(default_names)
        field_name = default_names{field_idx};
        if ~isfield(cfg, field_name) || isempty(cfg.(field_name))
            cfg.(field_name) = default_fields.(field_name);
        end
    end

    if isempty(cfg.corr_z_threshold), cfg.corr_z_threshold = cfg.z_threshold; end
    if isempty(cfg.var_z_threshold), cfg.var_z_threshold = cfg.z_threshold; end
    if isempty(cfg.range_z_threshold), cfg.range_z_threshold = cfg.z_threshold; end
    if isempty(cfg.kurt_z_threshold), cfg.kurt_z_threshold = cfg.z_threshold; end
end
