function [bad_idx, details] = get_bad_channels(channels, cfg)
    cfg = bad_channel_cfg_apply_defaults(cfg);
    [zdetail, cfg] = compute_bad_channel_zscores(channels, cfg);
    mean_corr = zdetail.mean_corr;
    channel_variance = zdetail.variance;
    channel_range = zdetail.range;
    channel_kurtosis = zdetail.kurtosis;
    z_corr = zdetail.z_corr;
    z_var = zdetail.z_var;
    z_range = zdetail.z_range;
    z_kurt = zdetail.z_kurt;

    bad_corr_mask = build_feature_mask(mean_corr, z_corr, cfg.use_correlation, cfg.corr_z_threshold);
    bad_var_mask = build_feature_mask(channel_variance, z_var, cfg.use_variance, cfg.var_z_threshold);
    bad_range_mask = build_feature_mask(channel_range, z_range, cfg.use_range, cfg.range_z_threshold);
    bad_kurt_mask = build_feature_mask(channel_kurtosis, z_kurt, cfg.use_kurtosis, cfg.kurt_z_threshold);

    bad_mask = bad_corr_mask | bad_var_mask | bad_range_mask | bad_kurt_mask;
    bad_idx = find(bad_mask);

    details = struct( ...
        'mean_corr', mean_corr, ...
        'variance', channel_variance, ...
        'range', channel_range, ...
        'kurtosis', channel_kurtosis, ...
        'z_corr', z_corr, ...
        'z_var', z_var, ...
        'z_range', z_range, ...
        'z_kurt', z_kurt, ...
        'bad_corr_mask', bad_corr_mask, ...
        'bad_var_mask', bad_var_mask, ...
        'bad_range_mask', bad_range_mask, ...
        'bad_kurt_mask', bad_kurt_mask, ...
        'bad_mask', bad_mask, ...
        'z_threshold', cfg.z_threshold, ...
        'corr_z_threshold', cfg.corr_z_threshold, ...
        'var_z_threshold', cfg.var_z_threshold, ...
        'range_z_threshold', cfg.range_z_threshold, ...
        'kurt_z_threshold', cfg.kurt_z_threshold, ...
        'use_correlation', cfg.use_correlation, ...
        'use_variance', cfg.use_variance, ...
        'use_range', cfg.use_range, ...
        'use_kurtosis', cfg.use_kurtosis, ...
        'normalization', cfg.normalization, ...
        'trim_percent', cfg.trim_percent);
end

function bad_mask = build_feature_mask(feature_values, z_values, is_enabled, z_threshold)
    if ~is_enabled
        bad_mask = false(size(feature_values));
        return;
    end

    bad_mask = ~isfinite(feature_values) | abs(z_values) > z_threshold;
end