function rows = build_trial_rejection_rows(subject_idx, run_idx, class_label, channel_labels, trial_info, rejection_details)
    num_trials = numel(trial_info);
    rows = repmat(struct( ...
        'subject', 0, ...
        'run', 0, ...
        'class_code', 0, ...
        'class_label', "", ...
        'trial_in_run', 0, ...
        'stimulus_sample', 0, ...
        'movement_sample', 0, ...
        'reaction_time_sec', NaN, ...
        'rt_rejected', false, ...
        'amplitude_rejected_channel_count', 0, ...
        'amplitude_rejected_channels', "", ...
        'final_rejected_channel_count', 0, ...
        'final_rejected_channels', "", ...
        'trial_status', ""), num_trials, 1);

    for trial_idx = 1:num_trials
        amplitude_bad_idx = find(rejection_details.amplitude_bad_mask(trial_idx, :));
        amplitude_bad_labels = join_labels(channel_labels(amplitude_bad_idx));
        rt_rejected = rejection_details.rt_invalid_mask(trial_idx);

        if rt_rejected
            final_rejected_channel_count = numel(channel_labels);
            final_rejected_channels = "ALL_CHANNELS (reaction time)";
            trial_status = "rt_rejected";
        elseif isempty(amplitude_bad_idx)
            final_rejected_channel_count = 0;
            final_rejected_channels = "";
            trial_status = "good";
        else
            final_rejected_channel_count = numel(amplitude_bad_idx);
            final_rejected_channels = amplitude_bad_labels;
            trial_status = "channel_rejected";
        end

        rows(trial_idx, 1) = struct( ...
            'subject', subject_idx, ...
            'run', run_idx, ...
            'class_code', trial_info(trial_idx).stimulus_code, ...
            'class_label', string(class_label), ...
            'trial_in_run', trial_idx, ...
            'stimulus_sample', trial_info(trial_idx).stimulus_sample, ...
            'movement_sample', trial_info(trial_idx).movement_sample, ...
            'reaction_time_sec', trial_info(trial_idx).reaction_time_sec, ...
            'rt_rejected', rt_rejected, ...
            'amplitude_rejected_channel_count', numel(amplitude_bad_idx), ...
            'amplitude_rejected_channels', amplitude_bad_labels, ...
            'final_rejected_channel_count', final_rejected_channel_count, ...
            'final_rejected_channels', final_rejected_channels, ...
            'trial_status', trial_status);
    end
end

function labels_string = join_labels(labels)
    if isempty(labels)
        labels_string = "";
        return;
    end

    labels_string = string(strjoin(labels, ', '));
end
