function [good_mask, summary, details] = reject_bad_trials(epochs, trial_info, cfg)
    num_trials = size(epochs, 3);
    num_channels = size(epochs, 1);
    good_mask = true(num_trials, num_channels);

    if num_trials == 0
        summary = struct( ...
            'num_trials', 0, ...
            'num_rt_rejections', 0, ...
            'num_amplitude_rejection_trials', 0, ...
            'num_amplitude_rejected_channels', 0, ...
            'good_trial_percent_per_channel', nan(1, num_channels));
        details = struct( ...
            'reaction_times_sec', zeros(0, 1), ...
            'rt_invalid_mask', false(0, 1), ...
            'amplitude_bad_mask', false(0, num_channels), ...
            'max_amplitude_uv', zeros(0, num_channels), ...
            'final_bad_mask', false(0, num_channels));
        return;
    end

    reaction_times = nan(num_trials, 1);
    for trial_idx = 1:num_trials
        reaction_times(trial_idx) = trial_info(trial_idx).reaction_time_sec;
    end

    valid_rt_mask = ...
        ~isnan(reaction_times) & ...
        reaction_times >= cfg.reaction_time_window_sec(1) & ...
        reaction_times <= cfg.reaction_time_window_sec(2);

    rt_invalid_mask = ~valid_rt_mask;
    good_mask(rt_invalid_mask, :) = false;

    max_amplitude = permute(max(abs(epochs), [], 2), [3 1 2]);
    max_amplitude = reshape(max_amplitude, num_trials, num_channels);
    amplitude_bad_mask = max_amplitude > cfg.amplitude_threshold_uv;
    good_mask = good_mask & ~amplitude_bad_mask;
    final_bad_mask = ~good_mask;

    summary = struct( ...
        'num_trials', num_trials, ...
        'num_rt_rejections', sum(rt_invalid_mask), ...
        'num_amplitude_rejection_trials', sum(any(amplitude_bad_mask, 2)), ...
        'num_amplitude_rejected_channels', sum(amplitude_bad_mask, 'all'), ...
        'good_trial_percent_per_channel', 100 * mean(good_mask, 1));

    details = struct( ...
        'reaction_times_sec', reaction_times, ...
        'rt_invalid_mask', rt_invalid_mask, ...
        'amplitude_bad_mask', amplitude_bad_mask, ...
        'max_amplitude_uv', max_amplitude, ...
        'final_bad_mask', final_bad_mask);
end
