data_root = 'data';
output_root = 'output';
figures_root = fullfile(output_root, 'figures');
tables_root = fullfile(output_root, 'tables');
cache_root = fullfile(output_root, 'cache');
results_path = fullfile(output_root, 'preprocessing_results.mat');
binica_support_dir = 'eeglab_binica_support';

run_cache_cfg = struct( ...
    'enabled', true, ...
    'overwrite_existing', false);

num_subjects = 15;
num_runs = 10;
num_eeg_channels = 61;
raw_fs = 512;

filter_cfg = struct( ...
    'order', 4, ...
    'band_hz', [0.3 70]);

bad_channel_cfg = struct( ...
    'z_threshold', 5, ...
    'corr_z_threshold', 7, ...
    'var_z_threshold', 10, ...
    'range_z_threshold', 8, ...
    'kurt_z_threshold', 20, ...
    'use_correlation', true, ...
    'use_variance', true, ...
    'use_range', true, ...
    'use_kurtosis', true, ...
    'normalization', 'trimmed', ...
    'trim_percent', 10);

decimation_factor = 2;

ica_cfg = struct( ...
    'algorithm', 'auto', ...
    'heartbeat_sec', 30, ...
    'threshold', 0.7, ...
    'artifact_class_indices', [2 3 4 5 6]);

epoch_cfg = struct( ...
    'window_sec', [-2.5 6], ...
    'baseline_sec', [-0.2 0], ...
    'reaction_time_window_sec', [0.1 2.0], ...
    'amplitude_threshold_uv', 200);

movement_codes = 1536:1542;
movement_labels = { ...
    'elbow flexion', ...
    'elbow extension', ...
    'supination', ...
    'pronation', ...
    'close hand', ...
    'open hand', ...
    'rest'};

report_cfg = struct( ...
    'erp_channel_label', 'Cz', ...
    'd1_bad_channels_csv', fullfile(tables_root, 'D1_artifacted_channels.csv'), ...
    'd2_good_trials_csv', fullfile(tables_root, 'D2_good_trial_percentages.csv'), ...
    'd2_channel_labels', {{'FC4', 'FCC2h', 'Cz', 'CCP6h'}});
