data_root = 'data';
output_root = 'output';
figures_root = fullfile(output_root, 'figures');
tables_root = fullfile(output_root, 'tables');
results_path = fullfile(output_root, 'preprocessing_results.mat');

num_subjects = 15;
num_runs = 10;
num_eeg_channels = 61;
raw_fs = 512;

filter_cfg = struct( ...
    'order', 4, ...
    'band_hz', [0.3 70]);

bad_channel_cfg = struct( ...
    'corr_threshold', 0.55, ...
    'trim_percent', 10, ...
    'z_threshold', 5, ...
    'iqr_multiplier', 1.5);

decimation_factor = 3;

ica_cfg = struct( ...
    'threshold', 0.7, ...
    'artifact_class_indices', [2 3 4 5 6]);

epoch_cfg = struct( ...
    'window_sec', [-2.5 6], ...
    'baseline_sec', [-0.2 0], ...
    'reaction_time_window_sec', [0.1 2.0], ...
    'amplitude_threshold_uv', 200);

movement_codes = 1536:1542;
movement_labels = arrayfun(@(code) sprintf('code_%d', code), movement_codes, 'UniformOutput', false);
movement_labels{movement_codes == 1540} = 'close_hand';
movement_labels{movement_codes == 1541} = 'open_hand';

plot_cfg = struct( ...
    'enabled', true, ...
    'diagnostic_subjects', 1:min(2, num_subjects), ...
    'diagnostic_runs', 1:min(2, num_runs), ...
    'preview_sec', 10, ...
    'erp_channel_label', 'Cz', ...
    'channels_to_plot', {{'FC4', 'FCC2h', 'Cz', 'CCP6h'}});
